// Fold a pull into dev/corpus.json so the readings become regression-protected.
//
//   node dev/import.mjs <pulled.json> <id-prefix> "<source sentence>"
//
// WHY THIS EXISTS. corpus.json is what dev/replay.mjs asserts against, and it
// was being built by hand. dev/derive.mjs reads the pulls directly, so a pull
// could teach the model a band while never entering the regression suite - the
// model would fit it and nothing would notice if a later derive broke it. That
// is exactly what happened to hi-lift: 47 readings trained the bands and only
// one hi-lift reading was ever asserted.
//
// The filter here is deliberately the same shape as the deriver's: Duplex only,
// the calibrated pair only, both springs present, and a lift that is either
// plain standard or hi-lift with a number attached. A row that fails any of
// those is reported, not dropped quietly.
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const HERE = dirname(fileURLToPath(import.meta.url));
const [pullFile, prefix, sourceText] = process.argv.slice(2).filter((a) => a !== "--dense");

// --dense MARKS THE BATCH AS BOUNDARY-DENSE, which is not a judgement about its
// quality but about which fitter should see it.
//
// A batch sampled deliberately next to a fitted threshold is the right data for
// placing that threshold and the wrong data for fitting the rung's sMult, which
// every spring count of the rung shares and which dev/derive.mjs fits by
// maximising a COUNT of correctly snapped readings. Boundary readings are the
// ambiguous ones, so a few hundred outvote the ordinary doors: 353 of them moved
// sMult by up to 0.0073, which is 0.22" of active length on a 30" spring, applied
// to every door on the rung.
//
// Marked dense, they reach the band and threshold fitters and not the stiffness
// fit. Pass it for anything generated by dev/frac-refine.mjs.
const DENSE = process.argv.includes("--dense");

if (!pullFile || !prefix) {
    console.error("usage: node dev/import.mjs <pulled.json> <id-prefix> \"<source>\"");
    process.exit(1);
}

// The reference encodes our "LHR" (low headroom) track as radius 10 - it is a
// radius there, not a lift type, and the user confirmed the two are the same
// option on the web calculator. Verified on D525-216 at 600 lb / 8'0" /
// 2 springs: reference r10 gives multiplier 0.477011 and our LHR gives the
// same to 3.7e-07. Without this mapping every radius-10 reading arrives as
// radius "10", which the app does not offer, and is scored against the
// radius-15 baseline instead.
const REF_RADIUS = { 10: "LHR", 12: "12", 15: "15" };
const ourRadius = (r) => REF_RADIUS[Number(r)] ?? String(r);

const PAIR = '3 3/4" inside 6"';
const wire = (w) => `${w}"`;
const r2 = (x) => Math.round(x * 100) / 100;
const corpus = JSON.parse(readFileSync(join(HERE, "corpus.json"), "utf8"));

// IDENTITY IS THE INPUTS, NOT THE ID STRING.
//
// This deduplicated on a display id built from prefix, wire sizes, weight,
// height, spring count, hi-lift and target - with no DRUM and no RADIUS. Two
// readings that differed only in drum or in track radius collided, and the
// second was dropped as "already in corpus". The radius batch lost 71 of 171
// rows that way, which is why D400-96 and D525-216 ended up with no radius-12
// readings at all despite being swept at radius 12.
//
// An id is a label. What makes a reading distinct is what was asked of the
// reference, so that is what is compared - the same key the deriver dedups on.
const inputKey = (state) => [
    state.drum, state.springs, state.radius, state.liftType ?? "Standard",
    state.liftin ?? "", state.cycles, state.weight,
    state.doorHeightFeet, state.doorHeightInches ?? 0,
].join("|");

const have = new Set(corpus.readings.map((r) => inputKey(r.state)));
const usedIds = new Set(corpus.readings.map((r) => r.id));
const skipped = {};
const skip = (why) => { skipped[why] = (skipped[why] ?? 0) + 1; };
const added = [];

for (const r of JSON.parse(readFileSync(pullFile, "utf8"))) {
    if (r.error) {
        skip(`request error: ${r.error}`);
        continue;
    }

    const i = r.input;
    const d = r.data;

    if (!d || !d.innerSpring || !d.outerSpring) {
        skip("no spring in response");
        continue;
    }

    if ((i.assembly ?? "Duplex") !== "Duplex") {
        skip(`assembly ${i.assembly}`);
        continue;
    }

    if (Number(i.innerId) !== 3.75 || Number(i.outerId) !== 6) {
        skip(`spring ids ${i.innerId}/${i.outerId}`);
        continue;
    }

    const raw = i.lift ?? "Standard";
    const hi = raw === "HiLift" || raw === "Hi-Lift";

    if (!hi && raw !== "Standard") {
        skip(`unrecognised lift ${raw}`);
        continue;
    }

    if (hi && !(Number(i.hiLift) > 0)) {
        skip("hi-lift row without a hiLift value");
        continue;
    }

    const inner = d.innerSpring;
    const outer = d.outerSpring;
    const w = String(i.widthInches ?? 108);
    // The drum and the radius belong in the label too, so a reading can be
    // identified from its id without opening the file.
    const base = [
        prefix,
        i.drum.split(" ").pop().replace(/[^A-Za-z0-9]/g, ""),
        String(outer.wireSize).replace("0.", ""),
        String(inner.wireSize).replace("0.", ""),
        `${i.weight}lb`,
        `${i.heightInches}in`,
        `${i.springs}spr`,
        `r${i.radius}`,
        hi ? `hl${i.hiLift}` : null,
        `t${i.cycles}`,
    ].filter(Boolean).join("-");

    const state = {
        assembly: "Duplex",
        drum: i.drum,
        springId: PAIR,
        springs: i.springs,
        radius: ourRadius(i.radius),
        ...(hi ? { liftType: "Hi-Lift", liftin: String(i.hiLift) } : {}),
        cycles: Number(i.cycles).toLocaleString("en-US"),
        weight: String(i.weight),
        doorHeightFeet: Math.floor(i.heightInches / 12),
        doorHeightInches: i.heightInches % 12,
        doorWidthFeet: Math.floor(Number(w) / 12),
        doorWidthInches: Number(w) % 12,
    };

    const key = inputKey(state);

    if (have.has(key)) {
        skip("already in corpus (same inputs)");
        continue;
    }

    have.add(key);

    // Ids must still be unique even though they no longer define identity.
    let tag = base;
    let suffix = 2;

    while (usedIds.has(tag)) {
        tag = `${base}-${suffix++}`;
    }

    usedIds.add(tag);

    // "Please contact us" rides along with every answer and means nothing.
    const flagged = (r.messages ?? [])
        .filter((m) => !/contact us/i.test(m)).length > 0 || r.status !== "success";

    added.push({
        id: tag,
        ...(DENSE ? { dense: true } : {}),
        status: "verified",
        source: sourceText ?? `Reference calculator, automated pull ${pullFile}.`,
        state,
        expect: {
            duplexInnerWire: wire(inner.wireSize),
            duplexOuterWire: wire(outer.wireSize),
            duplexInnerLength: inner.springLength,
            duplexOuterLength: outer.springLength,
            duplexInnerWeight: r2(inner.springWeight),
            duplexOuterWeight: r2(outer.springWeight),
        },
        tolerance: { duplexInnerWeight: 0.02, duplexOuterWeight: 0.02 },
        referenceCycles: d.cycles,
        // WHETHER THE REFERENCE COMPLAINED. Recorded because a flagged
        // reading's LENGTH is the least trustworthy figure in the file - the
        // complaint is usually about length - while its WIRE choice is as good
        // as any. dev/derive.mjs uses this to take the pairing and the cycle
        // count from such a reading and leave its length out of the fit.
        //
        // It was not recorded before, so earlier batches have no flag and are
        // fitted whole; only readings imported from here carry it.
        ...(flagged ? { flagged: true } : {}),
    });
}

corpus.readings.push(...added);
writeFileSync(join(HERE, "corpus.json"), JSON.stringify(corpus, null, 1) + "\n");

console.log(`${added.length} reading(s) added -> corpus.json (now ${corpus.readings.length})`);

if (Object.keys(skipped).length) {
    console.log("skipped:");
    for (const [why, n] of Object.entries(skipped).sort((a, b) => b[1] - a[1])) {
        console.log(`  ${String(n).padStart(4)}  ${why}`);
    }
}
